# ProGuard rules to keep required classes for release build
# Add rules generated by R8 missing_rules.txt

# Example keep rules for common missing classes (update with your missing_rules.txt if needed)
-keep class java.beans.** { *; }
-keep class org.conscrypt.** { *; }
-keep class org.w3c.dom.bootstrap.** { *; }
-keep class com.fasterxml.jackson.** { *; }
-keep class okhttp3.** { *; }
-dontwarn java.beans.**
-dontwarn org.conscrypt.**
-dontwarn org.w3c.dom.bootstrap.**
-dontwarn com.fasterxml.jackson.**
-dontwarn okhttp3.**
# Added to fix R8 missing class warnings (from missing_rules.txt)
-dontwarn java.beans.ConstructorProperties
-dontwarn java.beans.Transient
-dontwarn org.conscrypt.Conscrypt
-dontwarn org.conscrypt.OpenSSLProvider
-dontwarn org.w3c.dom.bootstrap.DOMImplementationRegistry
